# Generated by Django 4.0.3 on 2022-04-21 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Personal', 'Personal'), ('Errands', 'Errands'), ('Work', 'Work'), ('Friends', 'Friends'), ('Special Occasion', 'Special Occasion'), ('Classes', 'Classes'), ('Extracricular', 'Extracricular'), ('Random', 'Random'), ('Un-assigned', 'Un-assigned')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('discription', models.CharField(max_length=250)),
                ('date_time', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='main_app.categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
