# Generated by Django 4.0.4 on 2022-04-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_task_date_time_task_createddate_task_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
